travis:
  secure:
    BINSTAR_TOKEN: YwrfrJOSwuKzRxugmp6J+I3Q8SoXHhqxPvucL/oCKLwRFlNjkoGfK6gdIUw0eOJ02hlokayM/gJrs6FRhU5572loTDCkaCb+25iij4KSX7rg4KnXx0PtivbKMcEz86S7jmNRz3HEa9PCjvXcEpD8SXj9zA6o27sb/+mDFr9PuvhMQWxco0ObuPNV6KoH8kKWWUf1I5ANXIj45UFBfaMQUaoV+l2ekFhuTfR5vIXEg47wWDC+GQ0ilLexzVMjotUZnYuI4CceRKrDNuay4SpdBR2bBNogcqh4VCvnggfmcYXmqctVjjd5V4mVOumbH9ylqnHgLfr0ebadxkyMSJmoUayQbyubSGly8PvD57gShjWq7e0yocSXTg5RP0j6k3a8lYGTAey3Ys4zs0H+wZgdw7ZqXFtolh5JMi7WDKBDlMTw7be09C2DBg7cUHN2CXQlmzZAivwbATFHirsslXkOTWdGZOTPiOLBJy3RT0YynwX5AvHdhIixT0O1Np6oP2WUilAqoJlnO+OQOF6LKSE2EJEOm7umPLUZuIztJXYQPmsnE/zVzcJ41wmGz1yHs2iFAHtkXaOVbrU2OwbjK73t8Si9VCJPrn9Q7AQsTFhz8c+zQftsus/jJQnFTQugDQIjD87V4EGvugFRdRcLR9AaON1mLRq6vZqLvO4qX4pB+XU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
